name: Generate Snake

on:
  schedule:
    - cron: "0 5 * * *"  # Запуск каждый день в 05:00 по UTC
  workflow_dispatch:  # Возможность ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонирование репозитория
      - uses: actions/checkout@v2

      # Шаг 2: Генерация змейки
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: VikkMoor  # Замените на ваше имя пользователя

      # Шаг 3: Сохранение SVG-файла
      - name: Save Snake SVG
        run: |
          mkdir -p dist
          mv github-contribution-grid-snake.svg dist/github-contribution-grid-snake.svg

      # Шаг 4: Загрузка змейки на GitHub Pages
      - name: Deploy Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages  # Ветка, в которую будет произведён деплой
          build_dir: ./dist  # Директория с вашим сгенерированным SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

