name: Generate Snake

on:
  # Schedule is using cron syntax. Below runs at 05:00 AM UTC daily
  schedule:
    - cron: "0 5 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: VikkMoor  # Замените 'username' на ваше имя пользователя GitHub
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
