name: Generate Snake

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: VikkMoor  # Замените на ваше имя пользователя

      - name: Upload Snake to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

